language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_API_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master