language: node_js
node_js:
 - "node"

cache: npm

script: ./build.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_API_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: dist
  target_branch: master
  on:
    branch: dev